[alias]
xtask = "run --package xtask --release --bin xtask --"
test-root = [
    "test",
    "--workspace",
    "--all-features",
    "--all-targets",
    "--config",
    "target.\"cfg(all())\".runner=\"/usr/bin/sudo -E\"",
    "--",
    "--test-threads=1"
]

integration-test = [
    "test",
    "--test", "integration_tests",
    "--features", "finder",
    "--config",
    "target.\"cfg(all())\".runner=\"/usr/bin/sudo -E\"",
    "--",
    "--nocapture",
    "--test-threads=1"
]

coverage = [
    "tarpaulin",
    "--workspace",
    "--all-features",
    "--bin", "dosr",
    "--bin", "chsr",
    "--lib",
    "--timeout",
    "120",
    "--exclude-files",
    "build.rs", "xtask/src/*",
    "-e",
    "xtask",
    "--out", "Html",
    "--out", "Xml",
]

[env]
RAR_CFG_TYPE = "json"
RAR_CFG_PATH = "/etc/security/rootasrole.json"
RAR_CFG_DATA_PATH = "/etc/security/rootasrole.json"
RAR_PAM_SERVICE = "dosr"
RAR_BIN_PATH = "/usr/bin"
RAR_CFG_IMMUTABLE = "true"
RAR_CHSR_EDITOR_PATH = "/usr/bin/vim"
RAR_TIMEOUT_TYPE = "ppid"
RAR_TIMEOUT_DURATION = "00:05:00"
RAR_TIMEOUT_MAX_USAGE = ""
RAR_PATH_DEFAULT = "delete"
RAR_PATH_ADD_LIST = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
RAR_PATH_REMOVE_LIST = ""
RAR_ENV_DEFAULT = "delete"
RAR_ENV_KEEP_LIST = "HOME,USER,LOGNAME,COLORS,DISPLAY,HOSTNAME,KRB5CCNAME,LS_COLORS,PS1,PS2,XAUTHORY,XAUTHORIZATION,XDG_CURRENT_DESKTOP"
RAR_ENV_CHECK_LIST = "COLORTERM,LANG,LANGUAGE,LC_.*,LINGUAS,TERM,TZ"
RAR_ENV_DELETE_LIST = "PS4,SHELLOPTS,PERLLIB,PERL5LIB,PERL5OPT,PYTHONINSPECT"
RAR_ENV_SET_LIST = ""
RAR_ENV_OVERRIDE_BEHAVIOR = "false"
RAR_AUTHENTICATION = "perform"
RAR_EXEC_INFO_DISPLAY = "hide"
RAR_USER_CONSIDERED = "user"
RAR_BOUNDING = "strict"
RAR_UMASK = "0022"
RAR_MAX_LOCKFILE_RETRIES = "10"
RAR_LOCKFILE_RETRY_INTERVAL = "1"
RAR_TIMEOUT_STORAGE = "/var/run/rar/ts"